### ISSUE TITLE
[Real Issue] Exception if ai-labeler.yml was provided

### ISSUE THREAD

**Issue by edelciomolina** [jlowin/ai-labeler#23]
When the /.github/ai-labeler.yml file exists, an error occurs when attempting to create the new label. However, even when the labels already exist, the error persists.

Here is the error, and below are my files for reference.

```sh
with:
    openai-api-key: ***
    include-repo-labels: true
    controlflow-llm-model: openai/gpt-4o-mini
    github-token: ***
    config-path: .github/ai-labeler.yml
    dry-run: false
/usr/bin/docker run --name aaed[3](https://github.com/simplificaci/secure/actions/runs/12560079917/job/35016803436#step:4:3)bebf763d0ecf449d8819561e5ab68[4](https://github.com/simplificaci/secure/actions/runs/12560079917/job/35016803436#step:4:4)19_a0a8bd --label 2aaed3 --workdir /github/workspace --rm -e "INPUT_OPENAI-API-KEY" -e "INPUT_INCLUDE-REPO-LABELS" -e "INPUT_CONTROLFLOW-LLM-MODEL" -e "INPUT_ANTHROPIC-API-KEY" -e "INPUT_GITHUB-TOKEN" -e "INPUT_CONFIG-PATH" -e "INPUT_DRY-RUN" -e "INPUT_EVENT-NUMBER" -e "OPENAI_API_KEY" -e "ANTHROPIC_API_KEY" -e "CONTROLFLOW_LLM_MODEL" -e "GITHUB_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/secure/secure":"/github/workspace" 2aaed3:bebf763d0ecf449d8819[5](https://github.com/simplificaci/secure/actions/runs/12560079917/job/35016803436#step:4:5)61e5ab68419
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/ai_labeler/label_workflow.py", line 11[6](https://github.com/simplificaci/secure/actions/runs/12560079917/job/35016803436#step:4:6), in <module>
    run_label_workflow_from_env()
  File "/usr/local/lib/python3.12/site-packages/ai_labeler/label_workflow.py", line 20, in run_label_workflow_from_env
    return run_label_workflow(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ai_labeler/label_workflow.py", line 64, in run_label_workflow
    available_labels = get_available_labels_from_config(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ai_labeler/github.py", line 122, in get_available_labels_from_config
    create_label(gh_client, name=cfg.name, description=cfg.description or "")
  File "/usr/local/lib/python3.12/site-packages/ai_labeler/github.py", line 101, in create_label
    repo.create_label(name=name, description=description, color="ededed")
  File "/usr/local/lib/python3.12/site-packages/github/Repository.py", line 1506, in create_label
    headers, data = self._requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/github/Requester.py", line 586, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/github/Requester.py", line [7](https://github.com/simplificaci/secure/actions/runs/12560079917/job/35016803436#step:4:7)44, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "Label", "code": "already_exists", "field": "name"}], "documentation_url": "https://docs.github.com/rest/issues/labels#create-a-label", "status": "422"}
Label bug was not found on the repository, creating...
``` 

[job-logs.txt](https://github.com/user-attachments/files/18281786/job-logs.txt)
[issues-ai-label.yml.txt](https://github.com/user-attachments/files/18281790/issues-ai-label.yml.txt)
[ai-labeler.yml.txt](https://github.com/user-attachments/files/18281791/ai-labeler.yml.txt)

**Comment by edelciomolina** [comment]
Thinking better... in your Action, you are using the ai-labeler.yml file, and it should work! I then tried using your YML, which is more streamlined, but the error persisted, so I believe something is related to my list of labels, which is probably collected earlier.

Here are all my labels: 
[labels.json](https://github.com/user-attachments/files/18281897/labels.json)

**Comment by edelciomolina** [comment]
## Issue Found
If you already have a label with the same name but different from what is in the ai-labeler.yml file, the error will occur. For example, if you have a label named `BUG`, but mention `bug` in the file, the exception occurs.

## Fix
See https://github.com/jlowin/ai-labeler/pull/25
